sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd

reviewed:
  npm:
    - fs.realpath
    - '@httptoolkit/websocket-stream'
    - bl
    - crypto-js
    - ieee754
    - readable-stream
    - string_decoder
    - tslib-1.14.1
    - tslib-2.8.1
    - typedarray
