# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process
# from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Gitleaks secret detection
  secret_detection:
    name: Gitleaks secret detection
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Detect leaks
        run: |
          docker run --rm \
            -v $(pwd):/repo \
            -v $(pwd)/.gitleaks.toml:/repo/.gitleaks.toml \
            zricethezav/gitleaks:latest detect \
            --source="/repo" \
            --verbose \
            --redact \
            --config="/repo/.gitleaks.toml"

  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Move the committed index.js file
        run: mv dist/index.js /tmp

      - name: Rebuild with tsc
        run: npm run build

      - name: Rebuild the index.js file
        run: npm run release

      - name: Compare the expected and actual index.js files
        run: git diff --ignore-all-space dist/index.js /tmp/index.js
        id: diff

      # If index.js was different from expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: index.js
          path: dist/index.js
          overwrite: true
