name: Test
on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format-check

      - name: Run tests
        shell: bash
        run: |
          if [ "${{ matrix.runs-on }}" = "windows-latest" ]; then
            npm run test
          else
            NODE_OPTIONS=--experimental-vm-modules npm run test
          fi

      # Test empty directory handling
      - name: Create empty directory
        run: mkdir -p path/to/empty-dir

      - name: Upload empty directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: empty-dir-test
          path: path/to/empty-dir
          if-no-files-found: warn

      # Test special character handling
      - name: Create files with special characters
        run: |
          mkdir -p "path/to/special chars"
          echo "File with spaces" > "path/to/special chars/file with spaces.txt"
          echo "File with symbols" > "path/to/special chars/file-with-@#$symbols.txt"

      - name: Upload special characters files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: special-chars-test
          path: "path/to/special chars/**"

      # Test large number of files
      - name: Create many small files
        run: |
          mkdir -p path/to/many-files
          for i in {1..100}; do
            echo "Content for file $i" > "path/to/many-files/file$i.txt"
          done
        shell: bash

      - name: Upload many files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: many-files-test
          path: path/to/many-files/*

      # Test different file types
      - name: Create different file types
        run: |
          mkdir -p path/to/file-types
          echo '{"key": "value"}' > path/to/file-types/test.json
          echo '<?xml version="1.0"?><root>test</root>' > path/to/file-types/test.xml
          echo 'binary content' > path/to/file-types/test.bin
          echo '#!/bin/bash\necho "test"' > path/to/file-types/test.sh
          chmod +x path/to/file-types/test.sh
        shell: bash

      - name: Upload different file types as artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-types-test
          path: path/to/file-types/*

      # Test regular artifact upload/download functionality
      - name: Create test files
        run: |
          mkdir -p path/to/dir-1
          mkdir -p path/to/dir-2
          mkdir -p path/to/dir-3
          echo "Lorem ipsum dolor sit amet" > path/to/dir-1/file1.txt
          echo "Hello world from file #2" > path/to/dir-2/file2.txt
          echo "This is going to be a test for a large enough file that should get compressed with GZip" > path/to/dir-3/gzip.txt

      - name: Upload single file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-a
          path: path/to/dir-1/file1.txt

      - name: Upload wildcard pattern as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wildcard-artifact
          path: path/**/dir*/

      - name: Upload GZip artifact
        uses: actions/upload-artifact@v4
        with:
          name: gzip-artifact
          path: path/to/dir-3/

      - name: Upload multi-path artifact
        uses: actions/upload-artifact@v4
        with:
          name: multi-path-artifact
          path: |
            path/to/dir-1/*
            path/to/dir-[23]/*
            !path/to/dir-3/*.txt

      # Download artifacts and verify
      - name: Download and verify single file artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-a
          path: some/new/path

      - name: Verify single file artifact
        run: |
          file="some/new/path/file1.txt"
          if [ ! -f "$file" ]; then
              echo "Expected file does not exist"
              exit 1
          fi
          if [ "$(cat "$file")" != "Lorem ipsum dolor sit amet" ]; then
              echo "File contents of downloaded artifact are incorrect"
              exit 1
          fi
        shell: bash

      # Verify empty directory test
      - name: Download empty directory artifact
        uses: actions/download-artifact@v4
        with:
          name: empty-dir-test
          path: empty-dir-test

      # Verify special characters test
      - name: Download special characters artifact
        uses: actions/download-artifact@v4
        with:
          name: special-chars-test
          path: special-chars-test

      - name: Verify special characters files
        run: |
          if [ ! -f "special-chars-test/file with spaces.txt" ]; then
              echo "File with spaces not found"
              exit 1
          fi
          if [ ! -f "special-chars-test/file-with-@#\$symbols.txt" ]; then
              echo "File with symbols not found"
              exit 1
          fi
        shell: bash

      # Verify many files test
      - name: Download many files artifact
        uses: actions/download-artifact@v4
        with:
          name: many-files-test
          path: many-files-test

      - name: Verify many files
        run: |
          fileCount=$(find many-files-test -type f | wc -l)
          if [ "$fileCount" -ne 100 ]; then
              echo "Expected 100 files, found $fileCount"
              exit 1
          fi
        shell: bash

      # Verify different file types test
      - name: Download file types artifact
        uses: actions/download-artifact@v4
        with:
          name: file-types-test
          path: file-types-test

      - name: Verify file types
        run: |
          files=("test.json" "test.xml" "test.bin" "test.sh")
          for file in "${files[@]}"; do
              if [ ! -f "file-types-test/$file" ]; then
                  echo "File $file not found"
                  exit 1
              fi
          done
          
          # Verify JSON content
          if [ "$(jq -r '.key' file-types-test/test.json)" != "value" ]; then
              echo "JSON content is incorrect"
              exit 1
          fi
          
          # Verify XML content
          if ! grep -q "<root>test</root>" file-types-test/test.xml; then
              echo "XML content is incorrect"
              exit 1
          fi
        shell: bash

      - name: Download and verify wildcard pattern artifact
        uses: actions/download-artifact@v4
        with:
          name: wildcard-artifact
          path: some/other/path

      - name: Verify wildcard pattern artifact
        run: |
          file1="some/other/path/to/dir-1/file1.txt"
          file2="some/other/path/to/dir-2/file2.txt"
          if [ ! -f "$file1" ] || [ ! -f "$file2" ]; then
              echo "Expected files do not exist"
              exit 1
          fi
          if [ "$(cat "$file1")" != "Lorem ipsum dolor sit amet" ] || [ "$(cat "$file2")" != "Hello world from file #2" ]; then
              echo "File contents of downloaded artifacts are incorrect"
              exit 1
          fi
        shell: bash

      - name: Download and verify GZip artifact
        uses: actions/download-artifact@v4
        with:
          name: gzip-artifact
          path: gzip/artifact/path

      - name: Verify GZip artifact
        run: |
          gzipFile="gzip/artifact/path/gzip.txt"
          if [ ! -f "$gzipFile" ]; then
              echo "Expected file does not exist"
              exit 1
          fi
          if ! grep -q "compressed with GZip" "$gzipFile"; then
              echo "File contents of downloaded artifact is incorrect"
              exit 1
          fi
        shell: bash

      - name: Download and verify multi-path artifact
        uses: actions/download-artifact@v4
        with:
          name: multi-path-artifact
          path: multi/artifact

      - name: Verify multi-path artifact
        run: |
          file1="multi/artifact/dir-1/file1.txt"
          file2="multi/artifact/dir-2/file2.txt"
          if [ ! -f "$file1" ] || [ ! -f "$file2" ]; then
              echo "Expected files do not exist"
              exit 1
          fi
          if [ "$(cat "$file1")" != "Lorem ipsum dolor sit amet" ] || [ "$(cat "$file2")" != "Hello world from file #2" ]; then
              echo "File contents of downloaded artifacts are incorrect"
              exit 1
          fi
        shell: bash