name: Test
on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      ARTIFACTS_S3_BUCKET: mock-bucket
      AWS_ACCESS_KEY_ID: mock-key
      AWS_SECRET_ACCESS_KEY: mock-secret
      AWS_REGION: us-east-1
      DEBUG: "1"
      MOCK_AWS_S3_PATH: /tmp/mock-s3

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup mock AWS environment
        run: |
          # Create mock directory structure for storing artifacts
          mkdir -p $MOCK_AWS_S3_PATH/$ARTIFACTS_S3_BUCKET
          
          # Set up mock AWS configuration
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          region = $AWS_REGION
          EOF

      - name: Compile
        run: npm run build

      - name: Add execution permissions
        run: chmod +x dist/index.js

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format-check

      - name: Prepare test files
        run: |
          # Create test directories and files
          mkdir -p test-files/empty-dir
          mkdir -p "test-files/special chars"
          echo "File with spaces" > "test-files/special chars/file with spaces.txt"
          echo "File with symbols" > "test-files/special chars/file-with-@#$symbols.txt"

      - name: Run unit tests
        run: NODE_OPTIONS=--experimental-vm-modules npm run test

      - name: Test empty directory upload
        env:
          INPUT_DIRECTION: upload
        run: |
          node ./dist/index.js \
            --path="test-files/empty-dir" \
            --name="Empty-Dir-Test" \
            --if-no-files-found="warn" \
            --artifact-bucket="mock-bucket"

      - name: Test special characters upload
        env:
          INPUT_DIRECTION: upload
        run: |
          node ./dist/index.js \
            --path="test-files/special chars/**" \
            --name="Special-Chars-Test" \
            --if-no-files-found="warn" \
            --artifact-bucket="mock-bucket"

      - name: Verify uploads
        run: |
          # Check empty directory
          if [ ! -d "$MOCK_AWS_S3_PATH/$ARTIFACTS_S3_BUCKET/ci-pipeline-upload-artifacts/Empty-Dir-Test" ]; then
            echo "Empty directory upload failed"
            exit 1
          fi
          
          # Check special characters directory
          if [ ! -d "$MOCK_AWS_S3_PATH/$ARTIFACTS_S3_BUCKET/ci-pipeline-upload-artifacts/Special-Chars-Test" ]; then
            echo "Special characters directory upload failed"
            exit 1
          fi
          
          # Check specific files
          if [ ! -f "$MOCK_AWS_S3_PATH/$ARTIFACTS_S3_BUCKET/ci-pipeline-upload-artifacts/Special-Chars-Test/file with spaces.txt" ]; then
            echo "File with spaces upload failed"
            exit 1
          fi
          
          if [ ! -f "$MOCK_AWS_S3_PATH/$ARTIFACTS_S3_BUCKET/ci-pipeline-upload-artifacts/Special-Chars-Test/file-with-@#\$symbols.txt" ]; then
            echo "File with symbols upload failed"
            exit 1
          fi
          
          echo "All upload verifications passed successfully"